# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-11 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180709_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_time',
            field=models.DateTimeField(auto_now=True, verbose_name='评论时间'),
        ),
    ]
